name: flutter_keyboard_visibility
description: Flutter plugin for discovering the state of the soft-keyboard visibility on Android and iOS.
version: 4.0.6
homepage: https://github.com/MisterJimson/flutter_keyboard_visibility
repository: https://github.com/MisterJimson/flutter_keyboard_visibility

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  meta: ">=1.0.0 <2.0.0"
  flutter_keyboard_visibility_platform_interface: ^1.0.1
  flutter:
    sdk: flutter


flutter:
  plugin:
    platforms:
      android:
        package: com.jrai.flutter_keyboard_visibility
        pluginClass: FlutterKeyboardVisibilityPlugin
      ios:
        pluginClass: FlutterKeyboardVisibilityPlugin
      # web:
      #   default_package: flutter_keyboard_visibility_web